version: '3.7'

volumes:
  bookmarko_data:
  bookmarko_data_pdadmin:

networks:
  frontend:
  backend:
    internal: true

services:
  postgres:
    image: postgres:14.1
    container_name: local_pgdb
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: bookmarko
      POSTGRES_PASSWORD: "MJhDm5mHr7_KswU48AiWKczMGywA6N-I"
    volumes:
      - bookmarko_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - bookmarko_data_pdadmin:/var/lib/pgadmin
    networks:
      - backend
  
  serverpod:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: serverpod
    depends_on:
      - postgres
    environment:
      runmode: development
    ports:
      - 5051:8080
    networks:
      - frontend
      - backend

  nginx:
    container_name: nginx
    depends_on:
      - serverpod
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/certs:/etc/nginx/certs/:ro
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
    networks:
      - frontend
      - backend
