version: '3.7'

services:
  serverpod:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: serverpod
    depends_on:
      - postgres
    environment:
      runmode: development
    ports:
      - 5051:8080

  postgres:
    image: postgres:14.1
    container_name: postgres
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: bookmarko
      POSTGRES_PASSWORD: "MJhDm5mHr7_KswU48AiWKczMGywA6N-I"
    volumes:
      - bookmarko_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - bookmarko_data_pdadmin:/var/lib/pgadmin

volumes:
  bookmarko_data:
  bookmarko_data_pdadmin:


